name: docker
on: [push, pull_request]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # - name: list directory
      #   run: ls
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "creds.json"
          json: ${{ secrets.CREDS }}
          dir: 'pyosolver/'
      # - name: aws access key id
      #   run: 'echo "$ACCESS_KEY" > ./aws_access_key.txt'
      #   shell: bash
      #   env:
      #     ACCESS_KEY : ${{secrets.AWS_ACCESS_KEY_ID}}
      # - name: aws secret key
      #   run: 'echo "$SECRET_KEY" > ./aws_secret.txt'
      #   shell: bash
      #   env:
      #     SECRET_KEY : ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: build dockerfiles
        run: ./build.sh
      - name: run docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
            # https://docs.docker.com/compose/reference/overview/
            cli-args: "up -d"
      # - name: kafka producer
      #   run: docker exec -it jupyterlab "python3 pyosolver/src/main/python/reddit/reddit_producer.py"
      # - name: reddit streaming
      #   run: docker exec -it jupyterlab "python3 pyosolver/src/main/python/reddit/reddit_streaming.py"

