name: python
on: [push, pull_request]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "creds.json"
          json: ${{ secrets.CREDS }}
          dir: './'
      - name: pip install
        run: pip3 install -r src/main/python/pyosolver/requirements.txt
      - name: setup
        run: cd src/main/python/pyosolver && python3 setup.py bdist_wheel
      # - name: python3 setup.py
      #   run: python3 setup.py bdist_wheel
      # - name: pytest
      #   run: cd src/tests/python && pytest -v tests.py
